//HintName: MyApp_AuthFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class AuthFsm
{
    private global::MyApp.Auth _state = global::MyApp.Auth.ValidatingToken;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.Auth Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.T trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.Auth.ValidatingToken, global::MyApp.T.Done) => Fire(global::MyApp.Auth.ValidatingToken, global::MyApp.Auth.Renewing, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.Auth from, global::MyApp.Auth to, global::MyApp.T trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.Auth.ValidatingToken;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.Auth state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.Auth state, global::MyApp.T trigger)
    {
        switch (state)
        {
            case global::MyApp.Auth.ValidatingToken: OnExitValidatingToken(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.Auth state, global::MyApp.Auth from)
    {
        switch (state)
        {
            case global::MyApp.Auth.Renewing: OnEnterRenewing(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>ValidatingToken</c>.</summary>
    partial void OnExitValidatingToken(global::MyApp.T on);
    /// <summary>Called after entering <c>Renewing</c>.</summary>
    partial void OnEnterRenewing(global::MyApp.Auth from);
}
