//HintName: MyApp_ParentMachine.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class ParentMachine
{
    private global::MyApp.ParentState _state = global::MyApp.ParentState.Idle;

    private readonly global::MyApp.LoadingFsm _subFsm_Loading = new();

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.ParentState Current => _state;

    private bool TryFireSubMachine(global::MyApp.Trigger trigger) => _state switch
    {
        global::MyApp.ParentState.Loading => _subFsm_Loading.TryFire(trigger),
        _ => false
    };

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        if (TryFireSubMachine(trigger)) return true;

        return (Current, trigger) switch
        {
            (global::MyApp.ParentState.Idle, global::MyApp.Trigger.Start) => Fire(global::MyApp.ParentState.Idle, global::MyApp.ParentState.Loading, trigger),
            (global::MyApp.ParentState.Loading, global::MyApp.Trigger.Cancel) => Fire(global::MyApp.ParentState.Loading, global::MyApp.ParentState.Idle, trigger),
            (global::MyApp.ParentState.Loading, global::MyApp.Trigger.Complete) => Fire(global::MyApp.ParentState.Loading, global::MyApp.ParentState.Done, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.ParentState from, global::MyApp.ParentState to, global::MyApp.Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        if (to == global::MyApp.ParentState.Loading)
        {
            _subFsm_Loading.Reset();
        }
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.ParentState.Idle;
        _subFsm_Loading.Reset();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.ParentState state)
    {
        _state = state;
        switch (state)
        {
            case global::MyApp.ParentState.Loading: _subFsm_Loading.Reset(); break;
            default: break;
        }
    }

    private void OnExit(global::MyApp.ParentState state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.ParentState.Idle: OnExitIdle(trigger); break;
            case global::MyApp.ParentState.Loading: OnExitLoading(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.ParentState state, global::MyApp.ParentState from)
    {
        switch (state)
        {
            case global::MyApp.ParentState.Loading: OnEnterLoading(from); break;
            case global::MyApp.ParentState.Idle: OnEnterIdle(from); break;
            case global::MyApp.ParentState.Done: OnEnterDone(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Idle</c>.</summary>
    partial void OnExitIdle(global::MyApp.Trigger on);
    /// <summary>Called before leaving <c>Loading</c>.</summary>
    partial void OnExitLoading(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>Loading</c>.</summary>
    partial void OnEnterLoading(global::MyApp.ParentState from);
    /// <summary>Called after entering <c>Idle</c>.</summary>
    partial void OnEnterIdle(global::MyApp.ParentState from);
    /// <summary>Called after entering <c>Done</c>.</summary>
    partial void OnEnterDone(global::MyApp.ParentState from);
}
