//HintName: MyApp_TopFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class TopFsm
{
    private global::MyApp.L1 _state = global::MyApp.L1.A;

    private readonly global::MyApp.MidFsm _subFsm_A = new();

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.L1 Current => _state;

    private bool TryFireSubMachine(global::MyApp.Trigger trigger) => _state switch
    {
        global::MyApp.L1.A => _subFsm_A.TryFire(trigger),
        _ => false
    };

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        if (TryFireSubMachine(trigger)) return true;

        return (Current, trigger) switch
        {
            (global::MyApp.L1.A, global::MyApp.Trigger.Reset) => Fire(global::MyApp.L1.A, global::MyApp.L1.B, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.L1 from, global::MyApp.L1 to, global::MyApp.Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        if (to == global::MyApp.L1.A)
        {
            _subFsm_A.Reset();
        }
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.L1.A;
        _subFsm_A.Reset();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.L1 state)
    {
        _state = state;
        switch (state)
        {
            case global::MyApp.L1.A: _subFsm_A.Reset(); break;
            default: break;
        }
    }

    private void OnExit(global::MyApp.L1 state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.L1.A: OnExitA(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.L1 state, global::MyApp.L1 from)
    {
        switch (state)
        {
            case global::MyApp.L1.B: OnEnterB(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>A</c>.</summary>
    partial void OnExitA(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>B</c>.</summary>
    partial void OnEnterB(global::MyApp.L1 from);
}
