//HintName: MyApp_ConnFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class ConnFsm
{
    private global::MyApp.Conn _state = global::MyApp.Conn.Resolving;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.Conn Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.T trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.Conn.Resolving, global::MyApp.T.Done) => Fire(global::MyApp.Conn.Resolving, global::MyApp.Conn.Handshaking, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.Conn from, global::MyApp.Conn to, global::MyApp.T trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.Conn.Resolving;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.Conn state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.Conn state, global::MyApp.T trigger)
    {
        switch (state)
        {
            case global::MyApp.Conn.Resolving: OnExitResolving(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.Conn state, global::MyApp.Conn from)
    {
        switch (state)
        {
            case global::MyApp.Conn.Handshaking: OnEnterHandshaking(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Resolving</c>.</summary>
    partial void OnExitResolving(global::MyApp.T on);
    /// <summary>Called after entering <c>Handshaking</c>.</summary>
    partial void OnEnterHandshaking(global::MyApp.Conn from);
}
