//HintName: MyApp_LeafFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class LeafFsm
{
    private global::MyApp.L3 _state = global::MyApp.L3.P;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.L3 Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.L3.P, global::MyApp.Trigger.Tick) => Fire(global::MyApp.L3.P, global::MyApp.L3.Q, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.L3 from, global::MyApp.L3 to, global::MyApp.Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.L3.P;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.L3 state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.L3 state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.L3.P: OnExitP(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.L3 state, global::MyApp.L3 from)
    {
        switch (state)
        {
            case global::MyApp.L3.Q: OnEnterQ(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>P</c>.</summary>
    partial void OnExitP(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>Q</c>.</summary>
    partial void OnEnterQ(global::MyApp.L3 from);
}
