//HintName: MyApp_Machine.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class Machine
{
    private global::MyApp.Outer _state = global::MyApp.Outer.Idle;

    private readonly global::MyApp.ConnFsm _subFsm_Connecting = new();
    private readonly global::MyApp.AuthFsm _subFsm_Authenticated = new();

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.Outer Current => _state;

    private bool TryFireSubMachine(global::MyApp.T trigger) => _state switch
    {
        global::MyApp.Outer.Connecting => _subFsm_Connecting.TryFire(trigger),
        global::MyApp.Outer.Authenticated => _subFsm_Authenticated.TryFire(trigger),
        _ => false
    };

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.T trigger)
    {
        if (TryFireSubMachine(trigger)) return true;

        return (Current, trigger) switch
        {
            (global::MyApp.Outer.Idle, global::MyApp.T.Begin) => Fire(global::MyApp.Outer.Idle, global::MyApp.Outer.Connecting, trigger),
            (global::MyApp.Outer.Connecting, global::MyApp.T.Done) => Fire(global::MyApp.Outer.Connecting, global::MyApp.Outer.Authenticated, trigger),
            (global::MyApp.Outer.Authenticated, global::MyApp.T.Restart) => Fire(global::MyApp.Outer.Authenticated, global::MyApp.Outer.Idle, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.Outer from, global::MyApp.Outer to, global::MyApp.T trigger)
    {
        OnExit(from, trigger);
        _state = to;
        if (to == global::MyApp.Outer.Connecting)
        {
            _subFsm_Connecting.Reset();
        }
        if (to == global::MyApp.Outer.Authenticated)
        {
            _subFsm_Authenticated.Reset();
        }
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.Outer.Idle;
        _subFsm_Connecting.Reset();
        _subFsm_Authenticated.Reset();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.Outer state)
    {
        _state = state;
        switch (state)
        {
            case global::MyApp.Outer.Connecting: _subFsm_Connecting.Reset(); break;
            case global::MyApp.Outer.Authenticated: _subFsm_Authenticated.Reset(); break;
            default: break;
        }
    }

    private void OnExit(global::MyApp.Outer state, global::MyApp.T trigger)
    {
        switch (state)
        {
            case global::MyApp.Outer.Idle: OnExitIdle(trigger); break;
            case global::MyApp.Outer.Connecting: OnExitConnecting(trigger); break;
            case global::MyApp.Outer.Authenticated: OnExitAuthenticated(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.Outer state, global::MyApp.Outer from)
    {
        switch (state)
        {
            case global::MyApp.Outer.Connecting: OnEnterConnecting(from); break;
            case global::MyApp.Outer.Authenticated: OnEnterAuthenticated(from); break;
            case global::MyApp.Outer.Idle: OnEnterIdle(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Idle</c>.</summary>
    partial void OnExitIdle(global::MyApp.T on);
    /// <summary>Called before leaving <c>Connecting</c>.</summary>
    partial void OnExitConnecting(global::MyApp.T on);
    /// <summary>Called before leaving <c>Authenticated</c>.</summary>
    partial void OnExitAuthenticated(global::MyApp.T on);
    /// <summary>Called after entering <c>Connecting</c>.</summary>
    partial void OnEnterConnecting(global::MyApp.Outer from);
    /// <summary>Called after entering <c>Authenticated</c>.</summary>
    partial void OnEnterAuthenticated(global::MyApp.Outer from);
    /// <summary>Called after entering <c>Idle</c>.</summary>
    partial void OnEnterIdle(global::MyApp.Outer from);
}
