//HintName: MyApp_MidFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class MidFsm
{
    private global::MyApp.L2 _state = global::MyApp.L2.X;

    private readonly global::MyApp.LeafFsm _subFsm_X = new();

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.L2 Current => _state;

    private bool TryFireSubMachine(global::MyApp.Trigger trigger) => _state switch
    {
        global::MyApp.L2.X => _subFsm_X.TryFire(trigger),
        _ => false
    };

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        if (TryFireSubMachine(trigger)) return true;

        return (Current, trigger) switch
        {
            (global::MyApp.L2.X, global::MyApp.Trigger.Tick) => Fire(global::MyApp.L2.X, global::MyApp.L2.Y, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.L2 from, global::MyApp.L2 to, global::MyApp.Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        if (to == global::MyApp.L2.X)
        {
            _subFsm_X.Reset();
        }
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.L2.X;
        _subFsm_X.Reset();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.L2 state)
    {
        _state = state;
        switch (state)
        {
            case global::MyApp.L2.X: _subFsm_X.Reset(); break;
            default: break;
        }
    }

    private void OnExit(global::MyApp.L2 state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.L2.X: OnExitX(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.L2 state, global::MyApp.L2 from)
    {
        switch (state)
        {
            case global::MyApp.L2.Y: OnEnterY(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>X</c>.</summary>
    partial void OnExitX(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>Y</c>.</summary>
    partial void OnEnterY(global::MyApp.L2 from);
}
