//HintName: MyApp.Orders`1+Handlers`1+OrderMachine`1.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial record struct Orders<TKey>
{
partial class Handlers<@event>
{
partial class OrderMachine<TOrder> : System.IDisposable
{
    private long _state = (long)global::MyApp.State.Idle;

    private System.Threading.Timer? _timer_Pending_Expire;
    /// <summary>Current state (thread-safe read via <see cref="System.Threading.Volatile"/>).</summary>
    public global::MyApp.State Current => (global::MyApp.State)System.Threading.Volatile.Read(ref _state);

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> atomically via <c>Interlocked.CompareExchange</c>.
    /// Spins until the CAS succeeds or no matching transition exists.
    /// Returns <c>true</c> if the transition occurred.
    /// Entry and exit hooks fire after the CAS and are not synchronized — they may interleave with hooks from concurrent callers.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        while (true)
        {
            var current = (global::MyApp.State)System.Threading.Volatile.Read(ref _state);
            global::MyApp.State? next = (current, trigger) switch
            {
                (global::MyApp.State.Idle, global::MyApp.Trigger.Submit) => (global::MyApp.State?)global::MyApp.State.Pending,
                (global::MyApp.State.Pending, global::MyApp.Trigger.Complete) => (global::MyApp.State?)global::MyApp.State.Done,
                (global::MyApp.State.Pending, global::MyApp.Trigger.Expire) => (global::MyApp.State?)global::MyApp.State.Idle,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state, (long)next.Value, (long)current) == (long)current)
            {
                OnExit(current, trigger);
                OnEnter(next.Value, current);
                if (current == global::MyApp.State.Pending)
                    _timer_Pending_Expire?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                if (next.Value == global::MyApp.State.Pending)
                {
                    var __t = _timer_Pending_Expire;
                    if (__t is null)
                    {
                        var __new = new System.Threading.Timer(
                            static s => ((OrderMachine<TOrder>)s!).TryFire(global::MyApp.Trigger.Expire),
                            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                        __t = System.Threading.Interlocked.CompareExchange(ref _timer_Pending_Expire, __new, null) ?? __new;
                        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
                    }
                    __t.Change(500, System.Threading.Timeout.Infinite);
                }
                return true;
            }
            // Lost CAS race — retry with fresh current
        }
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = (long)global::MyApp.State.Idle;
        ArmInitialStateTimers();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.State state)
    {
        _state = (long)state;
        ArmInitialStateTimers();
    }

    private void OnExit(global::MyApp.State state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.State.Idle: OnExitIdle(trigger); break;
            case global::MyApp.State.Pending: OnExitPending(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.State state, global::MyApp.State from)
    {
        switch (state)
        {
            case global::MyApp.State.Pending: OnEnterPending(from); break;
            case global::MyApp.State.Done: OnEnterDone(from); break;
            case global::MyApp.State.Idle: OnEnterIdle(from); break;
        }
    }

    // ── Partial hooks — implement what you need, leave the rest ─────────────
    // Note: guards are not generated in concurrent mode (TOCTOU risk).
    /// <summary>Called after leaving <c>Idle</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitIdle(global::MyApp.Trigger on);
    /// <summary>Called after leaving <c>Pending</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitPending(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>Pending</c>. May be called from multiple threads.</summary>
    partial void OnEnterPending(global::MyApp.State from);
    /// <summary>Called after entering <c>Done</c>. May be called from multiple threads.</summary>
    partial void OnEnterDone(global::MyApp.State from);
    /// <summary>Called after entering <c>Idle</c>. May be called from multiple threads.</summary>
    partial void OnEnterIdle(global::MyApp.State from);

    // ── IDisposable — disposes timer fields. Idempotent (Timer.Dispose is idempotent).
    /// <summary>Disposes all timers owned by this machine.</summary>
    public void Dispose()
    {
        _timer_Pending_Expire?.Dispose();
        System.GC.SuppressFinalize(this);
    }

    /// <summary>Arms timers for any timed edges whose From state matches the current state.</summary>
    private void ArmInitialStateTimers()
    {
        var current = Current;
        if (current == global::MyApp.State.Pending)
        {
            var __t = _timer_Pending_Expire;
            if (__t is null)
            {
                var __new = new System.Threading.Timer(
                    static s => ((OrderMachine<TOrder>)s!).TryFire(global::MyApp.Trigger.Expire),
                    this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                __t = System.Threading.Interlocked.CompareExchange(ref _timer_Pending_Expire, __new, null) ?? __new;
                if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
            }
            __t.Change(500, System.Threading.Timeout.Infinite);
        }
    }

    /// <summary>Generator-emitted partial hook invoked from the constructor. Arms initial-state timers.</summary>
    private void HookConstructor()
    {
        ArmInitialStateTimers();
    }

    /// <summary>Default generator-emitted constructor; calls HookConstructor() to arm initial-state timers.</summary>
    public OrderMachine()
    {
        HookConstructor();
    }
}
}
}
