//HintName: MyApp_LightSwitch.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial struct LightSwitch
{
    private global::MyApp.State _state = global::MyApp.State.Off;

    /// <summary>Creates the machine in its declared initial state.</summary>
    public LightSwitch()
    {
    }

    /// <summary>Current state of the machine.</summary>
    public readonly global::MyApp.State Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.Trigger trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.State.Off, global::MyApp.Trigger.Flip) => Fire(global::MyApp.State.Off, global::MyApp.State.On, trigger),
            (global::MyApp.State.On, global::MyApp.Trigger.Flip) => Fire(global::MyApp.State.On, global::MyApp.State.Off, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.State from, global::MyApp.State to, global::MyApp.Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.State.Off;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.State state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.State state, global::MyApp.Trigger trigger)
    {
        switch (state)
        {
            case global::MyApp.State.Off: OnExitOff(trigger); break;
            case global::MyApp.State.On: OnExitOn(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.State state, global::MyApp.State from)
    {
        switch (state)
        {
            case global::MyApp.State.On: OnEnterOn(from); break;
            case global::MyApp.State.Off: OnEnterOff(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Off</c>.</summary>
    partial void OnExitOff(global::MyApp.Trigger on);
    /// <summary>Called before leaving <c>On</c>.</summary>
    partial void OnExitOn(global::MyApp.Trigger on);
    /// <summary>Called after entering <c>On</c>.</summary>
    partial void OnEnterOn(global::MyApp.State from);
    /// <summary>Called after entering <c>Off</c>.</summary>
    partial void OnEnterOff(global::MyApp.State from);
}
