//HintName: Resilience_CircuitBreakerFsm.g.cs
// <auto-generated />
#nullable enable

namespace Resilience;

partial class CircuitBreakerFsm
{
    private long _state = (long)CbState.Closed;

    /// <summary>Current state (thread-safe read via <see cref="System.Threading.Volatile"/>).</summary>
    public CbState Current => (CbState)System.Threading.Volatile.Read(ref _state);

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> atomically via <c>Interlocked.CompareExchange</c>.
    /// Spins until the CAS succeeds or no matching transition exists.
    /// Returns <c>true</c> if the transition occurred.
    /// </summary>
    public bool TryFire(CbTrigger trigger)
    {
        while (true)
        {
            var current = (CbState)System.Threading.Volatile.Read(ref _state);
            CbState? next = (current, trigger) switch
            {
                (CbState.Closed, CbTrigger.Trip) => (CbState?)CbState.Open,
                (CbState.Open, CbTrigger.Probe) => (CbState?)CbState.HalfOpen,
                (CbState.HalfOpen, CbTrigger.Reset) => (CbState?)CbState.Closed,
                (CbState.HalfOpen, CbTrigger.Trip) => (CbState?)CbState.Open,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state, (long)next.Value, (long)current) == (long)current)
            {
                OnExit(current, trigger);
                OnEnter(next.Value, current);
                return true;
            }
            // Lost CAS race — retry with fresh current
        }
    }

    private void OnExit(CbState state, CbTrigger trigger)
    {
        switch (state)
        {
            case CbState.Closed: OnExitClosed(trigger); break;
            case CbState.Open: OnExitOpen(trigger); break;
            case CbState.HalfOpen: OnExitHalfOpen(trigger); break;
        }
    }

    private void OnEnter(CbState state, CbState from)
    {
        switch (state)
        {
            case CbState.Open: OnEnterOpen(from); break;
            case CbState.HalfOpen: OnEnterHalfOpen(from); break;
            case CbState.Closed: OnEnterClosed(from); break;
        }
    }

    // ── Partial hooks — implement what you need, leave the rest ─────────────
    // Note: guards are not generated in concurrent mode (TOCTOU risk).
    /// <summary>Called after leaving <c>Closed</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitClosed(CbTrigger on);
    /// <summary>Called after leaving <c>Open</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitOpen(CbTrigger on);
    /// <summary>Called after leaving <c>HalfOpen</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitHalfOpen(CbTrigger on);
    /// <summary>Called after entering <c>Open</c>. May be called from multiple threads.</summary>
    partial void OnEnterOpen(CbState from);
    /// <summary>Called after entering <c>HalfOpen</c>. May be called from multiple threads.</summary>
    partial void OnEnterHalfOpen(CbState from);
    /// <summary>Called after entering <c>Closed</c>. May be called from multiple threads.</summary>
    partial void OnEnterClosed(CbState from);
}
