//HintName: MyApp_GuardedMachine.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class GuardedMachine
{
    private State _state = State.Idle;

    /// <summary>Current state of the machine.</summary>
    public State Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(Trigger trigger)
    {
        return (Current, trigger) switch
        {
            (State.Idle, Trigger.Submit)
                when GuardSubmit(State.Idle, Trigger.Submit)
                => Fire(State.Idle, State.Pending, trigger),
            (State.Pending, Trigger.Complete) => Fire(State.Pending, State.Done, trigger),
            _ => false
        };
    }

    private bool Fire(State from, State to, Trigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    private void OnExit(State state, Trigger trigger)
    {
        switch (state)
        {
            case State.Idle: OnExitIdle(trigger); break;
            case State.Pending: OnExitPending(trigger); break;
        }
    }

    private void OnEnter(State state, State from)
    {
        switch (state)
        {
            case State.Pending: OnEnterPending(from); break;
            case State.Done: OnEnterDone(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Guard for the Idle → Pending transition. Return <c>false</c> to block it.</summary>
    private partial bool GuardSubmit(State from, Trigger on);
    /// <summary>Called before leaving <c>Idle</c>.</summary>
    partial void OnExitIdle(Trigger on);
    /// <summary>Called before leaving <c>Pending</c>.</summary>
    partial void OnExitPending(Trigger on);
    /// <summary>Called after entering <c>Pending</c>.</summary>
    partial void OnEnterPending(State from);
    /// <summary>Called after entering <c>Done</c>.</summary>
    partial void OnEnterDone(State from);
}
