//HintName: MyApp_Order.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class Order
{
    private global::MyApp.OS _state = global::MyApp.OS.Idle;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.OS Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.OT trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.OS.Idle, global::MyApp.OT.Submit) => Fire(global::MyApp.OS.Idle, global::MyApp.OS.Submitted, trigger),
            (global::MyApp.OS.Submitted, global::MyApp.OT.Ship)
                when GuardShip(global::MyApp.OS.Submitted, global::MyApp.OT.Ship)
                => Fire(global::MyApp.OS.Submitted, global::MyApp.OS.Shipped, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.OS from, global::MyApp.OS to, global::MyApp.OT trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.OS.Idle;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.OS state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.OS state, global::MyApp.OT trigger)
    {
        switch (state)
        {
            case global::MyApp.OS.Idle: OnExitIdle(trigger); break;
            case global::MyApp.OS.Submitted: OnExitSubmitted(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.OS state, global::MyApp.OS from)
    {
        switch (state)
        {
            case global::MyApp.OS.Submitted: OnEnterSubmitted(from); break;
            case global::MyApp.OS.Shipped: OnEnterShipped(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Guard for the Submitted → Shipped transition on <c>Ship</c>. Implement this method; return <c>false</c> to block the transition.</summary>
    private partial bool GuardShip(global::MyApp.OS from, global::MyApp.OT on);
    /// <summary>Called before leaving <c>Idle</c>.</summary>
    partial void OnExitIdle(global::MyApp.OT on);
    /// <summary>Called before leaving <c>Submitted</c>.</summary>
    partial void OnExitSubmitted(global::MyApp.OT on);
    /// <summary>Called after entering <c>Submitted</c>.</summary>
    partial void OnEnterSubmitted(global::MyApp.OS from);
    /// <summary>Called after entering <c>Shipped</c>.</summary>
    partial void OnEnterShipped(global::MyApp.OS from);

    /// <summary>Mermaid stateDiagram-v2 representation of this state machine.</summary>
    public const string MermaidDiagram = @"stateDiagram-v2
    [*] --> Idle
    Idle --> Submitted: Submit
    Submitted --> Shipped: Ship [guard]
    Shipped --> [*]";
}
