//HintName: MyApp_LoadingFsm.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class LoadingFsm
{
    private global::MyApp.LoadingState _state = global::MyApp.LoadingState.Fetching;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.LoadingState Current => _state;

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.AppTrigger trigger)
    {
        return (Current, trigger) switch
        {
            (global::MyApp.LoadingState.Fetching, global::MyApp.AppTrigger.Tick) => Fire(global::MyApp.LoadingState.Fetching, global::MyApp.LoadingState.Parsing, trigger),
            (global::MyApp.LoadingState.Parsing, global::MyApp.AppTrigger.Complete) => Fire(global::MyApp.LoadingState.Parsing, global::MyApp.LoadingState.Done, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.LoadingState from, global::MyApp.LoadingState to, global::MyApp.AppTrigger trigger)
    {
        OnExit(from, trigger);
        _state = to;
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.LoadingState.Fetching;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.LoadingState state)
    {
        _state = state;
    }

    private void OnExit(global::MyApp.LoadingState state, global::MyApp.AppTrigger trigger)
    {
        switch (state)
        {
            case global::MyApp.LoadingState.Fetching: OnExitFetching(trigger); break;
            case global::MyApp.LoadingState.Parsing: OnExitParsing(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.LoadingState state, global::MyApp.LoadingState from)
    {
        switch (state)
        {
            case global::MyApp.LoadingState.Parsing: OnEnterParsing(from); break;
            case global::MyApp.LoadingState.Done: OnEnterDone(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Fetching</c>.</summary>
    partial void OnExitFetching(global::MyApp.AppTrigger on);
    /// <summary>Called before leaving <c>Parsing</c>.</summary>
    partial void OnExitParsing(global::MyApp.AppTrigger on);
    /// <summary>Called after entering <c>Parsing</c>.</summary>
    partial void OnEnterParsing(global::MyApp.LoadingState from);
    /// <summary>Called after entering <c>Done</c>.</summary>
    partial void OnEnterDone(global::MyApp.LoadingState from);
}
