//HintName: MyApp_Device.Group.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class Device
{
    // ── Part: Op ────────────────────────────────────────
    private long _state_Op = (long)global::MyApp.OpS.Idle;

    /// <summary>Current state of part "Op" (thread-safe read).</summary>
    public global::MyApp.OpS OpCurrent => (global::MyApp.OpS)System.Threading.Volatile.Read(ref _state_Op);

    /// <summary>Attempt to fire <paramref name="trigger"/> on part "Op". Returns <c>true</c> if the transition occurred.</summary>
    public bool TryFireOp(global::MyApp.OpT trigger)
    {
        while (true)
        {
            var current = (global::MyApp.OpS)System.Threading.Volatile.Read(ref _state_Op);
            global::MyApp.OpS? next = (current, trigger) switch
            {
                (global::MyApp.OpS.Idle, global::MyApp.OpT.Start) => (global::MyApp.OpS?)global::MyApp.OpS.Running,
                (global::MyApp.OpS.Running, global::MyApp.OpT.Stop) => (global::MyApp.OpS?)global::MyApp.OpS.Idle,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state_Op, (long)next.Value, (long)current) == (long)current)
            {
                OnExitOp(current, trigger);
                OnEnterOp(next.Value, current);
                return true;
            }
        }
    }

    private void OnExitOp(global::MyApp.OpS state, global::MyApp.OpT trigger)
    {
        switch (state)
        {
            case global::MyApp.OpS.Idle: OnExitOpIdle(trigger); break;
            case global::MyApp.OpS.Running: OnExitOpRunning(trigger); break;
        }
    }

    private void OnEnterOp(global::MyApp.OpS state, global::MyApp.OpS from)
    {
        switch (state)
        {
            case global::MyApp.OpS.Running: OnEnterOpRunning(from); break;
            case global::MyApp.OpS.Idle: OnEnterOpIdle(from); break;
        }
    }

    // ── Partial hooks for part "Op" — implement what you need
    /// <summary>Called after leaving <c>Idle</c> on part "Op".</summary>
    partial void OnExitOpIdle(global::MyApp.OpT on);
    /// <summary>Called after leaving <c>Running</c> on part "Op".</summary>
    partial void OnExitOpRunning(global::MyApp.OpT on);
    /// <summary>Called after entering <c>Running</c> on part "Op".</summary>
    partial void OnEnterOpRunning(global::MyApp.OpS from);
    /// <summary>Called after entering <c>Idle</c> on part "Op".</summary>
    partial void OnEnterOpIdle(global::MyApp.OpS from);

    // ── Part: Conn ────────────────────────────────────────
    private long _state_Conn = (long)global::MyApp.ConnS.Disconnected;

    /// <summary>Current state of part "Conn" (thread-safe read).</summary>
    public global::MyApp.ConnS ConnCurrent => (global::MyApp.ConnS)System.Threading.Volatile.Read(ref _state_Conn);

    /// <summary>Attempt to fire <paramref name="trigger"/> on part "Conn". Returns <c>true</c> if the transition occurred.</summary>
    public bool TryFireConn(global::MyApp.ConnT trigger)
    {
        while (true)
        {
            var current = (global::MyApp.ConnS)System.Threading.Volatile.Read(ref _state_Conn);
            global::MyApp.ConnS? next = (current, trigger) switch
            {
                (global::MyApp.ConnS.Disconnected, global::MyApp.ConnT.Connect) => (global::MyApp.ConnS?)global::MyApp.ConnS.Connected,
                (global::MyApp.ConnS.Connected, global::MyApp.ConnT.Disconnect) => (global::MyApp.ConnS?)global::MyApp.ConnS.Disconnected,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state_Conn, (long)next.Value, (long)current) == (long)current)
            {
                OnExitConn(current, trigger);
                OnEnterConn(next.Value, current);
                return true;
            }
        }
    }

    private void OnExitConn(global::MyApp.ConnS state, global::MyApp.ConnT trigger)
    {
        switch (state)
        {
            case global::MyApp.ConnS.Disconnected: OnExitConnDisconnected(trigger); break;
            case global::MyApp.ConnS.Connected: OnExitConnConnected(trigger); break;
        }
    }

    private void OnEnterConn(global::MyApp.ConnS state, global::MyApp.ConnS from)
    {
        switch (state)
        {
            case global::MyApp.ConnS.Connected: OnEnterConnConnected(from); break;
            case global::MyApp.ConnS.Disconnected: OnEnterConnDisconnected(from); break;
        }
    }

    // ── Partial hooks for part "Conn" — implement what you need
    /// <summary>Called after leaving <c>Disconnected</c> on part "Conn".</summary>
    partial void OnExitConnDisconnected(global::MyApp.ConnT on);
    /// <summary>Called after leaving <c>Connected</c> on part "Conn".</summary>
    partial void OnExitConnConnected(global::MyApp.ConnT on);
    /// <summary>Called after entering <c>Connected</c> on part "Conn".</summary>
    partial void OnEnterConnConnected(global::MyApp.ConnS from);
    /// <summary>Called after entering <c>Disconnected</c> on part "Conn".</summary>
    partial void OnEnterConnDisconnected(global::MyApp.ConnS from);


    /// <summary>Mermaid stateDiagram-v2 representation of this state-machine group.</summary>
    public const string MermaidDiagram = @"stateDiagram-v2
    state Op {
        [*] --> Idle
        Idle --> Running: Start
        Running --> Idle: Stop
    }
    state Conn {
        [*] --> Disconnected
        Disconnected --> Connected: Connect
        Connected --> Disconnected: Disconnect
    }";
}
