//HintName: MyApp_App.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class App
{
    private global::MyApp.AppState _state = global::MyApp.AppState.Idle;

    private readonly global::MyApp.LoadingFsm _subFsm_Loading = new();
    private global::MyApp.LoadingState _history_Loading;
    private bool _hasHistory_Loading;

    /// <summary>Current state of the machine.</summary>
    public global::MyApp.AppState Current => _state;

    private bool TryFireSubMachine(global::MyApp.AppTrigger trigger) => _state switch
    {
        global::MyApp.AppState.Loading => _subFsm_Loading.TryFire(trigger),
        _ => false
    };

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> from the current state.
    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.
    /// </summary>
    public bool TryFire(global::MyApp.AppTrigger trigger)
    {
        if (TryFireSubMachine(trigger)) return true;

        return (Current, trigger) switch
        {
            (global::MyApp.AppState.Idle, global::MyApp.AppTrigger.Begin) => Fire(global::MyApp.AppState.Idle, global::MyApp.AppState.Loading, trigger),
            (global::MyApp.AppState.Loading, global::MyApp.AppTrigger.Complete) => Fire(global::MyApp.AppState.Loading, global::MyApp.AppState.Ready, trigger),
            _ => false
        };
    }

    private bool Fire(global::MyApp.AppState from, global::MyApp.AppState to, global::MyApp.AppTrigger trigger)
    {
        OnExit(from, trigger);
        if (from == global::MyApp.AppState.Loading)
        {
            _history_Loading = _subFsm_Loading.Current;
            _hasHistory_Loading = true;
        }
        _state = to;
        if (to == global::MyApp.AppState.Loading)
        {
            if (_hasHistory_Loading) _subFsm_Loading.ResetTo(_history_Loading);
            else                       _subFsm_Loading.Reset();
        }
        OnEnter(to, from);
        return true;
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = global::MyApp.AppState.Idle;
        _subFsm_Loading.Reset();
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.AppState state)
    {
        _state = state;
        switch (state)
        {
            case global::MyApp.AppState.Loading: _subFsm_Loading.Reset(); break;
            default: break;
        }
    }

    private void OnExit(global::MyApp.AppState state, global::MyApp.AppTrigger trigger)
    {
        switch (state)
        {
            case global::MyApp.AppState.Idle: OnExitIdle(trigger); break;
            case global::MyApp.AppState.Loading: OnExitLoading(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.AppState state, global::MyApp.AppState from)
    {
        switch (state)
        {
            case global::MyApp.AppState.Loading: OnEnterLoading(from); break;
            case global::MyApp.AppState.Ready: OnEnterReady(from); break;
        }
    }


    // ── Partial hooks — implement what you need, leave the rest ─────────────
    /// <summary>Called before leaving <c>Idle</c>.</summary>
    partial void OnExitIdle(global::MyApp.AppTrigger on);
    /// <summary>Called before leaving <c>Loading</c>.</summary>
    partial void OnExitLoading(global::MyApp.AppTrigger on);
    /// <summary>Called after entering <c>Loading</c>.</summary>
    partial void OnEnterLoading(global::MyApp.AppState from);
    /// <summary>Called after entering <c>Ready</c>.</summary>
    partial void OnEnterReady(global::MyApp.AppState from);

    /// <summary>Mermaid stateDiagram-v2 representation of this state machine.</summary>
    public const string MermaidDiagram = @"stateDiagram-v2
    [*] --> Idle
    Idle --> Loading: Begin
    Loading --> Ready: Complete
    Ready --> [*]
    state Loading {
        state H as History
        [*] --> Fetching
        Fetching --> Parsing: Tick
        Parsing --> Done: Complete
        Done --> [*]
    }";
}
