//HintName: MyApp_DeviceTimed.Group.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class DeviceTimed : System.IDisposable
{
    // ── Part: Operational ────────────────────────────────────────
    private long _state_Operational = (long)global::MyApp.OpState.Idle;
    private System.Threading.Timer? _timer_Operational_Running_Fault;

    /// <summary>Current state of part "Operational" (thread-safe read).</summary>
    public global::MyApp.OpState OperationalCurrent => (global::MyApp.OpState)System.Threading.Volatile.Read(ref _state_Operational);

    /// <summary>Attempt to fire <paramref name="trigger"/> on part "Operational". Returns <c>true</c> if the transition occurred.</summary>
    public bool TryFireOperational(global::MyApp.OpTrigger trigger)
    {
        while (true)
        {
            var current = (global::MyApp.OpState)System.Threading.Volatile.Read(ref _state_Operational);
            global::MyApp.OpState? next = (current, trigger) switch
            {
                (global::MyApp.OpState.Idle, global::MyApp.OpTrigger.Start) => (global::MyApp.OpState?)global::MyApp.OpState.Running,
                (global::MyApp.OpState.Running, global::MyApp.OpTrigger.Fault) => (global::MyApp.OpState?)global::MyApp.OpState.Faulted,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state_Operational, (long)next.Value, (long)current) == (long)current)
            {
                OnExitOperational(current, trigger);
                OnEnterOperational(next.Value, current);
                if (current == global::MyApp.OpState.Running)
                    _timer_Operational_Running_Fault?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                if (next.Value == global::MyApp.OpState.Running)
                {
                    var __t = _timer_Operational_Running_Fault;
                    if (__t is null)
                    {
                        var __new = new System.Threading.Timer(
                            static s => ((DeviceTimed)s!).TryFireOperational(global::MyApp.OpTrigger.Fault),
                            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                        __t = System.Threading.Interlocked.CompareExchange(ref _timer_Operational_Running_Fault, __new, null) ?? __new;
                        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
                    }
                    __t.Change(10000, System.Threading.Timeout.Infinite);
                }
                return true;
            }
        }
    }

    private void OnExitOperational(global::MyApp.OpState state, global::MyApp.OpTrigger trigger)
    {
        switch (state)
        {
            case global::MyApp.OpState.Idle: OnExitOperationalIdle(trigger); break;
            case global::MyApp.OpState.Running: OnExitOperationalRunning(trigger); break;
        }
    }

    private void OnEnterOperational(global::MyApp.OpState state, global::MyApp.OpState from)
    {
        switch (state)
        {
            case global::MyApp.OpState.Running: OnEnterOperationalRunning(from); break;
            case global::MyApp.OpState.Faulted: OnEnterOperationalFaulted(from); break;
        }
    }

    // ── Partial hooks for part "Operational" — implement what you need
    /// <summary>Called after leaving <c>Idle</c> on part "Operational".</summary>
    partial void OnExitOperationalIdle(global::MyApp.OpTrigger on);
    /// <summary>Called after leaving <c>Running</c> on part "Operational".</summary>
    partial void OnExitOperationalRunning(global::MyApp.OpTrigger on);
    /// <summary>Called after entering <c>Running</c> on part "Operational".</summary>
    partial void OnEnterOperationalRunning(global::MyApp.OpState from);
    /// <summary>Called after entering <c>Faulted</c> on part "Operational".</summary>
    partial void OnEnterOperationalFaulted(global::MyApp.OpState from);

    private void ArmInitialStateTimers_Operational()
    {
        var current = OperationalCurrent;
        if (current == global::MyApp.OpState.Running)
        {
            var __t = _timer_Operational_Running_Fault;
            if (__t is null)
            {
                var __new = new System.Threading.Timer(
                    static s => ((DeviceTimed)s!).TryFireOperational(global::MyApp.OpTrigger.Fault),
                    this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                __t = System.Threading.Interlocked.CompareExchange(ref _timer_Operational_Running_Fault, __new, null) ?? __new;
                if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
            }
            __t.Change(10000, System.Threading.Timeout.Infinite);
        }
    }

    // ── Part: Connection ────────────────────────────────────────
    private long _state_Connection = (long)global::MyApp.ConnState.Disconnected;

    /// <summary>Current state of part "Connection" (thread-safe read).</summary>
    public global::MyApp.ConnState ConnectionCurrent => (global::MyApp.ConnState)System.Threading.Volatile.Read(ref _state_Connection);

    /// <summary>Attempt to fire <paramref name="trigger"/> on part "Connection". Returns <c>true</c> if the transition occurred.</summary>
    public bool TryFireConnection(global::MyApp.ConnTrigger trigger)
    {
        while (true)
        {
            var current = (global::MyApp.ConnState)System.Threading.Volatile.Read(ref _state_Connection);
            global::MyApp.ConnState? next = (current, trigger) switch
            {
                (global::MyApp.ConnState.Disconnected, global::MyApp.ConnTrigger.Connect) => (global::MyApp.ConnState?)global::MyApp.ConnState.Connected,
                (global::MyApp.ConnState.Connected, global::MyApp.ConnTrigger.Disconnect) => (global::MyApp.ConnState?)global::MyApp.ConnState.Disconnected,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state_Connection, (long)next.Value, (long)current) == (long)current)
            {
                OnExitConnection(current, trigger);
                OnEnterConnection(next.Value, current);
                return true;
            }
        }
    }

    private void OnExitConnection(global::MyApp.ConnState state, global::MyApp.ConnTrigger trigger)
    {
        switch (state)
        {
            case global::MyApp.ConnState.Disconnected: OnExitConnectionDisconnected(trigger); break;
            case global::MyApp.ConnState.Connected: OnExitConnectionConnected(trigger); break;
        }
    }

    private void OnEnterConnection(global::MyApp.ConnState state, global::MyApp.ConnState from)
    {
        switch (state)
        {
            case global::MyApp.ConnState.Connected: OnEnterConnectionConnected(from); break;
            case global::MyApp.ConnState.Disconnected: OnEnterConnectionDisconnected(from); break;
        }
    }

    // ── Partial hooks for part "Connection" — implement what you need
    /// <summary>Called after leaving <c>Disconnected</c> on part "Connection".</summary>
    partial void OnExitConnectionDisconnected(global::MyApp.ConnTrigger on);
    /// <summary>Called after leaving <c>Connected</c> on part "Connection".</summary>
    partial void OnExitConnectionConnected(global::MyApp.ConnTrigger on);
    /// <summary>Called after entering <c>Connected</c> on part "Connection".</summary>
    partial void OnEnterConnectionConnected(global::MyApp.ConnState from);
    /// <summary>Called after entering <c>Disconnected</c> on part "Connection".</summary>
    partial void OnEnterConnectionDisconnected(global::MyApp.ConnState from);


    /// <summary>Disposes all timers owned by this group.</summary>
    public void Dispose()
    {
        _timer_Operational_Running_Fault?.Dispose();
        System.GC.SuppressFinalize(this);
    }

    /// <summary>Generator-emitted partial hook invoked from the constructor.</summary>
    private void HookConstructor()
    {
        ArmInitialStateTimers_Operational();
    }

    public DeviceTimed()
    {
        HookConstructor();
    }
}
