//HintName: MyApp_Multi.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class Multi : System.IDisposable
{
    private long _state = (long)global::MyApp.MS.A;

    private System.Threading.Timer? _timer_A_ToB;
    private System.Threading.Timer? _timer_B_ToC;
    /// <summary>Current state (thread-safe read via <see cref="System.Threading.Volatile"/>).</summary>
    public global::MyApp.MS Current => (global::MyApp.MS)System.Threading.Volatile.Read(ref _state);

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> atomically via <c>Interlocked.CompareExchange</c>.
    /// Spins until the CAS succeeds or no matching transition exists.
    /// Returns <c>true</c> if the transition occurred.
    /// Entry and exit hooks fire after the CAS and are not synchronized — they may interleave with hooks from concurrent callers.
    /// </summary>
    public bool TryFire(global::MyApp.MT trigger)
    {
        while (true)
        {
            var current = (global::MyApp.MS)System.Threading.Volatile.Read(ref _state);
            global::MyApp.MS? next = (current, trigger) switch
            {
                (global::MyApp.MS.A, global::MyApp.MT.ToB) => (global::MyApp.MS?)global::MyApp.MS.B,
                (global::MyApp.MS.B, global::MyApp.MT.ToC) => (global::MyApp.MS?)global::MyApp.MS.C,
                (global::MyApp.MS.C, global::MyApp.MT.Reset) => (global::MyApp.MS?)global::MyApp.MS.A,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state, (long)next.Value, (long)current) == (long)current)
            {
                OnExit(current, trigger);
                OnEnter(next.Value, current);
                if (current == global::MyApp.MS.A)
                    _timer_A_ToB?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                if (current == global::MyApp.MS.B)
                    _timer_B_ToC?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                if (next.Value == global::MyApp.MS.A)
                {
                    var __t = _timer_A_ToB;
                    if (__t is null)
                    {
                        var __new = new System.Threading.Timer(
                            static s => ((Multi)s!).TryFire(global::MyApp.MT.ToB),
                            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                        __t = System.Threading.Interlocked.CompareExchange(ref _timer_A_ToB, __new, null) ?? __new;
                        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
                    }
                    __t.Change(1000, System.Threading.Timeout.Infinite);
                }
                if (next.Value == global::MyApp.MS.B)
                {
                    var __t = _timer_B_ToC;
                    if (__t is null)
                    {
                        var __new = new System.Threading.Timer(
                            static s => ((Multi)s!).TryFire(global::MyApp.MT.ToC),
                            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                        __t = System.Threading.Interlocked.CompareExchange(ref _timer_B_ToC, __new, null) ?? __new;
                        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
                    }
                    __t.Change(2000, System.Threading.Timeout.Infinite);
                }
                return true;
            }
            // Lost CAS race — retry with fresh current
        }
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = (long)global::MyApp.MS.A;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.MS state)
    {
        _state = (long)state;
    }

    private void OnExit(global::MyApp.MS state, global::MyApp.MT trigger)
    {
        switch (state)
        {
            case global::MyApp.MS.A: OnExitA(trigger); break;
            case global::MyApp.MS.B: OnExitB(trigger); break;
            case global::MyApp.MS.C: OnExitC(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.MS state, global::MyApp.MS from)
    {
        switch (state)
        {
            case global::MyApp.MS.B: OnEnterB(from); break;
            case global::MyApp.MS.C: OnEnterC(from); break;
            case global::MyApp.MS.A: OnEnterA(from); break;
        }
    }

    // ── Partial hooks — implement what you need, leave the rest ─────────────
    // Note: guards are not generated in concurrent mode (TOCTOU risk).
    /// <summary>Called after leaving <c>A</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitA(global::MyApp.MT on);
    /// <summary>Called after leaving <c>B</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitB(global::MyApp.MT on);
    /// <summary>Called after leaving <c>C</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitC(global::MyApp.MT on);
    /// <summary>Called after entering <c>B</c>. May be called from multiple threads.</summary>
    partial void OnEnterB(global::MyApp.MS from);
    /// <summary>Called after entering <c>C</c>. May be called from multiple threads.</summary>
    partial void OnEnterC(global::MyApp.MS from);
    /// <summary>Called after entering <c>A</c>. May be called from multiple threads.</summary>
    partial void OnEnterA(global::MyApp.MS from);

    // ── IDisposable — disposes timer fields. Idempotent (Timer.Dispose is idempotent).
    /// <summary>Disposes all timers owned by this machine.</summary>
    public void Dispose()
    {
        _timer_A_ToB?.Dispose();
        _timer_B_ToC?.Dispose();
        System.GC.SuppressFinalize(this);
    }

    /// <summary>Arms timers for any timed edges whose From state matches the current state.</summary>
    private void ArmInitialStateTimers()
    {
        var current = Current;
        if (current == global::MyApp.MS.A)
        {
            var __t = _timer_A_ToB;
            if (__t is null)
            {
                var __new = new System.Threading.Timer(
                    static s => ((Multi)s!).TryFire(global::MyApp.MT.ToB),
                    this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                __t = System.Threading.Interlocked.CompareExchange(ref _timer_A_ToB, __new, null) ?? __new;
                if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
            }
            __t.Change(1000, System.Threading.Timeout.Infinite);
        }
        if (current == global::MyApp.MS.B)
        {
            var __t = _timer_B_ToC;
            if (__t is null)
            {
                var __new = new System.Threading.Timer(
                    static s => ((Multi)s!).TryFire(global::MyApp.MT.ToC),
                    this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                __t = System.Threading.Interlocked.CompareExchange(ref _timer_B_ToC, __new, null) ?? __new;
                if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
            }
            __t.Change(2000, System.Threading.Timeout.Infinite);
        }
    }

    /// <summary>Generator-emitted partial hook invoked from the constructor. Arms initial-state timers.</summary>
    private void HookConstructor()
    {
        ArmInitialStateTimers();
    }

    /// <summary>Default generator-emitted constructor; calls HookConstructor() to arm initial-state timers.</summary>
    public Multi()
    {
        HookConstructor();
    }
}
