//HintName: MyApp_Watchdog.g.cs
// <auto-generated />
#nullable enable

namespace MyApp;

partial class Watchdog : System.IDisposable
{
    private long _state = (long)global::MyApp.WdState.Idle;

    private System.Threading.Timer? _timer_Working_Timeout;
    /// <summary>Current state (thread-safe read via <see cref="System.Threading.Volatile"/>).</summary>
    public global::MyApp.WdState Current => (global::MyApp.WdState)System.Threading.Volatile.Read(ref _state);

    /// <summary>
    /// Attempt to fire <paramref name="trigger"/> atomically via <c>Interlocked.CompareExchange</c>.
    /// Spins until the CAS succeeds or no matching transition exists.
    /// Returns <c>true</c> if the transition occurred.
    /// Entry and exit hooks fire after the CAS and are not synchronized — they may interleave with hooks from concurrent callers.
    /// </summary>
    public bool TryFire(global::MyApp.WdTrigger trigger)
    {
        while (true)
        {
            var current = (global::MyApp.WdState)System.Threading.Volatile.Read(ref _state);
            global::MyApp.WdState? next = (current, trigger) switch
            {
                (global::MyApp.WdState.Idle, global::MyApp.WdTrigger.Start) => (global::MyApp.WdState?)global::MyApp.WdState.Working,
                (global::MyApp.WdState.Working, global::MyApp.WdTrigger.Heartbeat) => (global::MyApp.WdState?)global::MyApp.WdState.Working,
                (global::MyApp.WdState.Working, global::MyApp.WdTrigger.Timeout) => (global::MyApp.WdState?)global::MyApp.WdState.Dead,
                _ => null
            };

            if (next is null) return false;

            if (System.Threading.Interlocked.CompareExchange(
                    ref _state, (long)next.Value, (long)current) == (long)current)
            {
                OnExit(current, trigger);
                OnEnter(next.Value, current);
                if (current == global::MyApp.WdState.Working)
                    _timer_Working_Timeout?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                if (next.Value == global::MyApp.WdState.Working)
                {
                    var __t = _timer_Working_Timeout;
                    if (__t is null)
                    {
                        var __new = new System.Threading.Timer(
                            static s => ((Watchdog)s!).TryFire(global::MyApp.WdTrigger.Timeout),
                            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);
                        __t = System.Threading.Interlocked.CompareExchange(ref _timer_Working_Timeout, __new, null) ?? __new;
                        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();
                    }
                    __t.Change(5000, System.Threading.Timeout.Infinite);
                }
                return true;
            }
            // Lost CAS race — retry with fresh current
        }
    }

    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    internal void Reset()
    {
        _state = (long)global::MyApp.WdState.Idle;
    }

    /// <summary>Sets the machine to <paramref name="state"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>
    /// <remarks>If <paramref name="state"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>
    internal void ResetTo(global::MyApp.WdState state)
    {
        _state = (long)state;
    }

    private void OnExit(global::MyApp.WdState state, global::MyApp.WdTrigger trigger)
    {
        switch (state)
        {
            case global::MyApp.WdState.Idle: OnExitIdle(trigger); break;
            case global::MyApp.WdState.Working: OnExitWorking(trigger); break;
        }
    }

    private void OnEnter(global::MyApp.WdState state, global::MyApp.WdState from)
    {
        switch (state)
        {
            case global::MyApp.WdState.Working: OnEnterWorking(from); break;
            case global::MyApp.WdState.Dead: OnEnterDead(from); break;
        }
    }

    // ── Partial hooks — implement what you need, leave the rest ─────────────
    // Note: guards are not generated in concurrent mode (TOCTOU risk).
    /// <summary>Called after leaving <c>Idle</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitIdle(global::MyApp.WdTrigger on);
    /// <summary>Called after leaving <c>Working</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>
    partial void OnExitWorking(global::MyApp.WdTrigger on);
    /// <summary>Called after entering <c>Working</c>. May be called from multiple threads.</summary>
    partial void OnEnterWorking(global::MyApp.WdState from);
    /// <summary>Called after entering <c>Dead</c>. May be called from multiple threads.</summary>
    partial void OnEnterDead(global::MyApp.WdState from);

    // ── IDisposable — disposes timer fields. Idempotent (Timer.Dispose is idempotent).
    /// <summary>Disposes all timers owned by this machine.</summary>
    public void Dispose()
    {
        _timer_Working_Timeout?.Dispose();
        System.GC.SuppressFinalize(this);
    }
}
