namespace ZeroAlloc.StateMachine.Generator;

using System.Linq;
using System.Text;

internal static class StateMachineWriter
{
    public static string Write(StateMachineModel model,
        System.Func<string, StateMachineModel?>? resolveSubMachine = null)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var keyword = model.IsStruct ? "partial struct" : "partial class";
        var disposableSuffix = HasAnyTimedEdge(model) ? " : System.IDisposable" : "";
        sb.AppendLine($"{keyword} {model.ClassName}{disposableSuffix}");
        sb.AppendLine("{");

        if (model.Concurrent)
            WriteConcurrentBody(sb, model);
        else
            WriteNonConcurrentBody(sb, model);

        WriteMermaidDiagram(sb, model, resolveSubMachine ?? (static _ => null));

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void WriteMermaidDiagram(StringBuilder sb, StateMachineModel m,
        System.Func<string, StateMachineModel?> resolveSubMachine)
    {
        if (!m.Diagram) return;

        var diagram = MermaidDiagramWriter.Write(m, resolveSubMachine);
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Mermaid stateDiagram-v2 representation of this state machine.</summary>");
        sb.Append($"    public const string MermaidDiagram = ");
        AppendQuotedMultiline(sb, diagram);
        sb.AppendLine(";");
    }

    private static void AppendQuotedMultiline(StringBuilder sb, string raw)
    {
        // Verbatim string literal: @"...". Quotes inside doubled.
        sb.Append("@\"");
        sb.Append(raw.Replace("\"", "\"\""));
        sb.Append('"');
    }

    // ── Non-concurrent ────────────────────────────────────────────────────────

    private static void WriteNonConcurrentBody(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;

        // State field
        sb.AppendLine($"    private {st} _state = {st}.{m.InitialState};");
        sb.AppendLine();

        // Sub-FSM + history fields (only if composites exist)
        WriteCompositeFields(sb, m);

        // Current property
        sb.AppendLine($"    /// <summary>Current state of the machine.</summary>");
        sb.AppendLine($"    public {st} Current => _state;");
        sb.AppendLine();

        // TryFireSubMachine dispatcher (only if composites exist)
        WriteTryFireSubMachine(sb, m);

        WriteNonConcurrentTryFire(sb, m);

        // Fire helper
        WriteNonConcurrentFire(sb, m);
        sb.AppendLine();

        // Reset / ResetTo — state-population mechanics (no OnExit/OnEnter)
        WriteResetMechanics(sb, m);
        sb.AppendLine();

        // OnExit dispatcher
        WriteOnExitDispatcher(sb, m);
        sb.AppendLine();

        // OnEnter dispatcher
        WriteOnEnterDispatcher(sb, m);
        sb.AppendLine();

        WritePartialStubs(sb, m);
    }

    private static void WriteCompositeFields(StringBuilder sb, StateMachineModel m)
    {
        if (m.CompositeStates.IsEmpty) return;

        // Sub-FSM instances (one per [CompositeState]).
        foreach (var c in m.CompositeStates)
        {
            sb.AppendLine($"    private readonly {c.SubMachineFqn} _subFsm_{c.State} = new();");
        }

        // History fields (one pair per [HistoryState] that matches a [CompositeState]).
        var historySet = new System.Collections.Generic.HashSet<string>(
            m.HistoryStates.Select(static h => h.State), StringComparer.Ordinal);
        foreach (var c in m.CompositeStates)
        {
            if (historySet.Contains(c.State))
            {
                sb.AppendLine($"    private {c.SubMachineStateTypeFqn} _history_{c.State};");
                sb.AppendLine($"    private bool _hasHistory_{c.State};");
            }
        }

        sb.AppendLine();
    }

    private static void WriteTryFireSubMachine(StringBuilder sb, StateMachineModel m)
    {
        if (m.CompositeStates.IsEmpty) return;

        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine($"    private bool TryFireSubMachine({tr} trigger) => _state switch");
        sb.AppendLine($"    {{");
        foreach (var c in m.CompositeStates)
        {
            sb.AppendLine($"        {st}.{c.State} => _subFsm_{c.State}.TryFire(trigger),");
        }
        sb.AppendLine($"        _ => false");
        sb.AppendLine($"    }};");
        sb.AppendLine();
    }

    private static void WriteNonConcurrentFire(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine($"    private bool Fire({st} from, {st} to, {tr} trigger)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        OnExit(from, trigger);");

        WriteFireCompositeBlocks(sb, m);

        sb.AppendLine($"        _state = to;");

        WriteFireEnterCompositeBlocks(sb, m);

        sb.AppendLine($"        OnEnter(to, from);");
        sb.AppendLine($"        return true;");
        sb.AppendLine($"    }}");
    }

    private static void WriteFireCompositeBlocks(StringBuilder sb, StateMachineModel m)
    {
        if (m.CompositeStates.IsEmpty || m.HistoryStates.IsEmpty) return;

        var st = m.StateTypeFqn;
        var historySet = new System.Collections.Generic.HashSet<string>(
            m.HistoryStates.Select(static h => h.State), StringComparer.Ordinal);

        // Capture history on exit (one block per [HistoryState] matching a composite).
        foreach (var c in m.CompositeStates)
        {
            if (historySet.Contains(c.State))
            {
                sb.AppendLine($"        if (from == {st}.{c.State})");
                sb.AppendLine($"        {{");
                sb.AppendLine($"            _history_{c.State} = _subFsm_{c.State}.Current;");
                sb.AppendLine($"            _hasHistory_{c.State} = true;");
                sb.AppendLine($"        }}");
            }
        }
    }

    private static void WriteFireEnterCompositeBlocks(StringBuilder sb, StateMachineModel m)
    {
        if (m.CompositeStates.IsEmpty) return;

        var st = m.StateTypeFqn;
        var historySet = new System.Collections.Generic.HashSet<string>(
            m.HistoryStates.Select(static h => h.State), StringComparer.Ordinal);

        // Reset/restore sub-FSM on enter (one block per [CompositeState]).
        foreach (var c in m.CompositeStates)
        {
            sb.AppendLine($"        if (to == {st}.{c.State})");
            sb.AppendLine($"        {{");
            if (historySet.Contains(c.State))
            {
                sb.AppendLine($"            if (_hasHistory_{c.State}) _subFsm_{c.State}.ResetTo(_history_{c.State});");
                sb.AppendLine($"            else                       _subFsm_{c.State}.Reset();");
            }
            else
            {
                sb.AppendLine($"            _subFsm_{c.State}.Reset();");
            }
            sb.AppendLine($"        }}");
        }
    }

    private static void WriteNonConcurrentTryFire(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Attempt to fire <paramref name=\"trigger\"/> from the current state.");
        sb.AppendLine($"    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public bool TryFire({tr} trigger)");
        sb.AppendLine($"    {{");

        if (m.CompositeStates.Length > 0)
        {
            sb.AppendLine($"        if (TryFireSubMachine(trigger)) return true;");
            sb.AppendLine();
        }

        sb.AppendLine($"        return (Current, trigger) switch");
        sb.AppendLine($"        {{");

        foreach (var t in m.Transitions)
        {
            if (t.HasGuard)
            {
                sb.AppendLine($"            ({st}.{t.From}, {tr}.{t.On})");
                sb.AppendLine($"                when Guard{t.On}({st}.{t.From}, {tr}.{t.On})");
                sb.AppendLine($"                => Fire({st}.{t.From}, {st}.{t.To}, trigger),");
            }
            else
            {
                sb.AppendLine($"            ({st}.{t.From}, {tr}.{t.On}) => Fire({st}.{t.From}, {st}.{t.To}, trigger),");
            }
        }

        sb.AppendLine($"            _ => false");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    private static void WriteOnExitDispatcher(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;
        var exitStates = m.Transitions.Select(static t => t.From).Distinct(StringComparer.Ordinal).ToArray();

        sb.AppendLine($"    private void OnExit({st} state, {tr} trigger)");
        sb.AppendLine($"    {{");
        if (exitStates.Length > 0)
        {
            sb.AppendLine($"        switch (state)");
            sb.AppendLine($"        {{");
            foreach (var s in exitStates)
                sb.AppendLine($"            case {st}.{s}: OnExit{s}(trigger); break;");
            sb.AppendLine($"        }}");
        }
        sb.AppendLine($"    }}");
    }

    private static void WriteOnEnterDispatcher(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var enterStates = m.Transitions.Select(static t => t.To).Distinct(StringComparer.Ordinal).ToArray();

        sb.AppendLine($"    private void OnEnter({st} state, {st} from)");
        sb.AppendLine($"    {{");
        if (enterStates.Length > 0)
        {
            sb.AppendLine($"        switch (state)");
            sb.AppendLine($"        {{");
            foreach (var s in enterStates)
                sb.AppendLine($"            case {st}.{s}: OnEnter{s}(from); break;");
            sb.AppendLine($"        }}");
        }
        sb.AppendLine($"    }}");
    }

    private static void WritePartialStubs(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine();
        sb.AppendLine($"    // ── Partial hooks — implement what you need, leave the rest ─────────────");

        // Guard stubs — defining declaration only; user must provide the implementing declaration.
        // If unimplemented, the compiler emits CS8795, telling the user to implement the guard.
        var guardedTransitions = m.Transitions.Where(static t => t.HasGuard).ToArray();
        foreach (var t in guardedTransitions)
        {
            sb.AppendLine($"    /// <summary>Guard for the {t.From} \u2192 {t.To} transition on <c>{t.On}</c>. Implement this method; return <c>false</c> to block the transition.</summary>");
            sb.AppendLine($"    private partial bool Guard{t.On}({st} from, {tr} on);");
        }

        // OnExit stubs — one per unique From state
        var exitStates = m.Transitions.Select(static t => t.From).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in exitStates)
        {
            sb.AppendLine($"    /// <summary>Called before leaving <c>{s}</c>.</summary>");
            sb.AppendLine($"    partial void OnExit{s}({tr} on);");
        }

        // OnEnter stubs — one per unique To state
        var enterStates = m.Transitions.Select(static t => t.To).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in enterStates)
        {
            sb.AppendLine($"    /// <summary>Called after entering <c>{s}</c>.</summary>");
            sb.AppendLine($"    partial void OnEnter{s}({st} from);");
        }
    }

    // ── Concurrent ───────────────────────────────────────────────────────────

    private static void WriteConcurrentBody(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        // Volatile long state field
        sb.AppendLine($"    private long _state = (long){st}.{m.InitialState};");
        sb.AppendLine();

        WriteTimerFields(sb, m);

        sb.AppendLine($"    /// <summary>Current state (thread-safe read via <see cref=\"System.Threading.Volatile\"/>).</summary>");
        sb.AppendLine($"    public {st} Current => ({st})System.Threading.Volatile.Read(ref _state);");
        sb.AppendLine();

        WriteConcurrentTryFire(sb, m);

        // Reset / ResetTo — state-population mechanics (no OnExit/OnEnter)
        WriteResetMechanics(sb, m);
        sb.AppendLine();

        // OnExit + OnEnter dispatchers — same as non-concurrent
        WriteOnExitDispatcher(sb, m);
        sb.AppendLine();
        WriteOnEnterDispatcher(sb, m);

        // Partial stubs — no guards in concurrent mode
        WriteConcurrentPartialStubs(sb, m);

        WriteDispose(sb, m);

        WriteArmInitialStateTimers(sb, m);

        WriteHookConstructorAndCtor(sb, m);
    }

    private static void WriteConcurrentTryFire(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Attempt to fire <paramref name=\"trigger\"/> atomically via <c>Interlocked.CompareExchange</c>.");
        sb.AppendLine($"    /// Spins until the CAS succeeds or no matching transition exists.");
        sb.AppendLine($"    /// Returns <c>true</c> if the transition occurred.");
        sb.AppendLine($"    /// Entry and exit hooks fire after the CAS and are not synchronized — they may interleave with hooks from concurrent callers.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public bool TryFire({tr} trigger)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        while (true)");
        sb.AppendLine($"        {{");
        sb.AppendLine($"            var current = ({st})System.Threading.Volatile.Read(ref _state);");
        sb.AppendLine($"            {st}? next = (current, trigger) switch");
        sb.AppendLine($"            {{");

        foreach (var t in m.Transitions)
            sb.AppendLine($"                ({st}.{t.From}, {tr}.{t.On}) => ({st}?){st}.{t.To},");

        sb.AppendLine($"                _ => null");
        sb.AppendLine($"            }};");
        sb.AppendLine();
        sb.AppendLine($"            if (next is null) return false;");
        sb.AppendLine();
        sb.AppendLine($"            if (System.Threading.Interlocked.CompareExchange(");
        sb.AppendLine($"                    ref _state, (long)next.Value, (long)current) == (long)current)");
        sb.AppendLine($"            {{");
        sb.AppendLine($"                OnExit(current, trigger);");
        sb.AppendLine($"                OnEnter(next.Value, current);");
        WriteTimerDisarmBlocks(sb, m, "                ", "current", partPrefix: null, m.StateTypeFqn);
        WriteTimerArmBlocks(sb, m, "                ", "next.Value", partPrefix: null, tryFireMethod: "TryFire", m.StateTypeFqn);
        sb.AppendLine($"                return true;");
        sb.AppendLine($"            }}");
        sb.AppendLine($"            // Lost CAS race — retry with fresh current");
        sb.AppendLine($"        }}");
        sb.AppendLine($"    }}");
        sb.AppendLine();
    }

    private static void WriteResetMechanics(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var assignInitial = m.Concurrent
            ? $"_state = (long){st}.{m.InitialState};"
            : $"_state = {st}.{m.InitialState};";
        var assignState = m.Concurrent
            ? "_state = (long)state;"
            : "_state = state;";

        sb.AppendLine($"    /// <summary>Resets the machine to its declared initial state. Does NOT fire OnExit/OnEnter -- state-population only.</summary>");
        sb.AppendLine($"    internal void Reset()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        {assignInitial}");

        // If this class itself has composites, reset each sub-FSM to its initial.
        foreach (var c in m.CompositeStates)
        {
            sb.AppendLine($"        _subFsm_{c.State}.Reset();");
        }

        sb.AppendLine($"    }}");
        sb.AppendLine();

        sb.AppendLine($"    /// <summary>Sets the machine to <paramref name=\"state\"/>. Does NOT fire OnExit/OnEnter -- state-population only.</summary>");
        sb.AppendLine($"    /// <remarks>If <paramref name=\"state\"/> is itself a composite, the sub-FSM is reset to its initial state (shallow history contract).</remarks>");
        sb.AppendLine($"    internal void ResetTo({st} state)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        {assignState}");

        if (m.CompositeStates.Length > 0)
        {
            sb.AppendLine($"        switch (state)");
            sb.AppendLine($"        {{");
            foreach (var c in m.CompositeStates)
            {
                sb.AppendLine($"            case {st}.{c.State}: _subFsm_{c.State}.Reset(); break;");
            }
            sb.AppendLine($"            default: break;");
            sb.AppendLine($"        }}");
        }

        sb.AppendLine($"    }}");
    }

    private static void WriteConcurrentPartialStubs(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeFqn;
        var tr = m.TriggerTypeFqn;

        sb.AppendLine();
        sb.AppendLine($"    // ── Partial hooks — implement what you need, leave the rest ─────────────");
        sb.AppendLine($"    // Note: guards are not generated in concurrent mode (TOCTOU risk).");

        var exitStates = m.Transitions.Select(static t => t.From).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in exitStates)
        {
            sb.AppendLine($"    /// <summary>Called after leaving <c>{s}</c> (fires after the CAS succeeds). May be called from multiple threads.</summary>");
            sb.AppendLine($"    partial void OnExit{s}({tr} on);");
        }

        var enterStates = m.Transitions.Select(static t => t.To).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in enterStates)
        {
            sb.AppendLine($"    /// <summary>Called after entering <c>{s}</c>. May be called from multiple threads.</summary>");
            sb.AppendLine($"    partial void OnEnter{s}({st} from);");
        }
    }

    // ── Timer emit helpers (B3 — [Transition(AfterMs)]) ──────────────────────

    private static void WriteTimerFields(StringBuilder sb, StateMachineModel m, string? partPrefix = null)
    {
        var timedEdges = m.Transitions.Where(static t => t.AfterMs > 0);
        if (partPrefix is null)
            timedEdges = timedEdges.Where(static t => t.Part is null);
        else
            timedEdges = timedEdges.Where(t => string.Equals(t.Part, partPrefix, StringComparison.Ordinal));

        foreach (var t in timedEdges)
        {
            var prefix = partPrefix is null ? string.Empty : $"{partPrefix}_";
            sb.AppendLine($"    private System.Threading.Timer? _timer_{prefix}{t.From}_{t.On};");
        }
    }

    private static void WriteTimerArmBlocks(StringBuilder sb, StateMachineModel m,
        string indent, string stateExpr, string? partPrefix, string tryFireMethod, string stateTypeFqn)
    {
        foreach (var t in m.Transitions)
        {
            if (t.AfterMs == 0) continue;
            if (!string.Equals(t.Part, partPrefix, StringComparison.Ordinal)) continue;

            var prefix = partPrefix is null ? string.Empty : $"{partPrefix}_";
            var field = $"_timer_{prefix}{t.From}_{t.On}";
            var triggerFqn = m.TriggerTypeFqn;

            sb.AppendLine($"{indent}if ({stateExpr} == {stateTypeFqn}.{t.From})");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    var __t = {field};");
            sb.AppendLine($"{indent}    if (__t is null)");
            sb.AppendLine($"{indent}    {{");
            sb.AppendLine($"{indent}        var __new = new System.Threading.Timer(");
            sb.AppendLine($"{indent}            static s => (({m.ClassName})s!).{tryFireMethod}({triggerFqn}.{t.On}),");
            sb.AppendLine($"{indent}            this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);");
            sb.AppendLine($"{indent}        __t = System.Threading.Interlocked.CompareExchange(ref {field}, __new, null) ?? __new;");
            sb.AppendLine($"{indent}        if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}    __t.Change({t.AfterMs}, System.Threading.Timeout.Infinite);");
            sb.AppendLine($"{indent}}}");
        }
    }

    private static void WriteTimerDisarmBlocks(StringBuilder sb, StateMachineModel m,
        string indent, string fromExpr, string? partPrefix, string stateTypeFqn)
    {
        foreach (var t in m.Transitions)
        {
            if (t.AfterMs == 0) continue;
            if (!string.Equals(t.Part, partPrefix, StringComparison.Ordinal)) continue;

            var prefix = partPrefix is null ? string.Empty : $"{partPrefix}_";
            var field = $"_timer_{prefix}{t.From}_{t.On}";
            sb.AppendLine($"{indent}if ({fromExpr} == {stateTypeFqn}.{t.From})");
            sb.AppendLine($"{indent}    {field}?.Change(System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);");
        }
    }

    private static bool HasAnyTimedEdge(StateMachineModel m) =>
        m.Transitions.Any(static t => t.AfterMs > 0);

    private static void WriteArmInitialStateTimers(StringBuilder sb, StateMachineModel m)
    {
        if (!HasAnyTimedEdge(m)) return;

        var st = m.StateTypeFqn;

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Arms timers for any timed edges whose From state matches the current state.</summary>");
        sb.AppendLine($"    private void ArmInitialStateTimers()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        var current = Current;");

        foreach (var t in m.Transitions)
        {
            if (t.AfterMs == 0) continue;
            if (t.Part is not null) continue;  // group parts handled separately

            var field = $"_timer_{t.From}_{t.On}";
            sb.AppendLine($"        if (current == {st}.{t.From})");
            sb.AppendLine($"        {{");
            sb.AppendLine($"            var __t = {field};");
            sb.AppendLine($"            if (__t is null)");
            sb.AppendLine($"            {{");
            sb.AppendLine($"                var __new = new System.Threading.Timer(");
            sb.AppendLine($"                    static s => (({m.ClassName})s!).TryFire({m.TriggerTypeFqn}.{t.On}),");
            sb.AppendLine($"                    this, System.Threading.Timeout.Infinite, System.Threading.Timeout.Infinite);");
            sb.AppendLine($"                __t = System.Threading.Interlocked.CompareExchange(ref {field}, __new, null) ?? __new;");
            sb.AppendLine($"                if (!System.Object.ReferenceEquals(__t, __new)) __new.Dispose();");
            sb.AppendLine($"            }}");
            sb.AppendLine($"            __t.Change({t.AfterMs}, System.Threading.Timeout.Infinite);");
            sb.AppendLine($"        }}");
        }

        sb.AppendLine($"    }}");
    }

    private static void WriteDispose(StringBuilder sb, StateMachineModel m)
    {
        if (!HasAnyTimedEdge(m)) return;

        sb.AppendLine();
        sb.AppendLine($"    // ── IDisposable — disposes timer fields. Idempotent (Timer.Dispose is idempotent).");
        sb.AppendLine($"    /// <summary>Disposes all timers owned by this machine.</summary>");
        sb.AppendLine($"    public void Dispose()");
        sb.AppendLine($"    {{");
        foreach (var t in m.Transitions)
        {
            if (t.AfterMs == 0) continue;
            var prefix = t.Part is null ? string.Empty : $"{t.Part}_";
            sb.AppendLine($"        _timer_{prefix}{t.From}_{t.On}?.Dispose();");
        }
        sb.AppendLine($"        System.GC.SuppressFinalize(this);");
        sb.AppendLine($"    }}");
    }

    private static void WriteHookConstructorAndCtor(StringBuilder sb, StateMachineModel m)
    {
        if (!HasAnyTimedEdge(m)) return;

        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Generator-emitted partial hook invoked from the constructor. Arms initial-state timers.</summary>");
        sb.AppendLine($"    private void HookConstructor()");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        ArmInitialStateTimers();");
        sb.AppendLine($"    }}");

        if (!m.HasUserCtor)
        {
            sb.AppendLine();
            sb.AppendLine($"    /// <summary>Default generator-emitted constructor; calls HookConstructor() to arm initial-state timers.</summary>");
            sb.AppendLine($"    public {m.ClassName}()");
            sb.AppendLine($"    {{");
            sb.AppendLine($"        HookConstructor();");
            sb.AppendLine($"    }}");
        }
    }
}
