namespace ZeroAlloc.StateMachine.Generator;

using System.Text;

internal static class StateMachineGroupWriter
{
    public static string Write(StateMachineGroupModel m)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (m.Namespace is not null)
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"partial class {m.ClassName}");
        sb.AppendLine("{");
        // Per-part emit lands in subsequent tasks.
        sb.AppendLine("}");
        return sb.ToString();
    }
}
