namespace ZeroAlloc.StateMachine.Generator;

using System.Collections.Generic;
using System.Linq;
using System.Text;

internal static class StateMachineWriter
{
    public static string Write(StateMachineModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace};");
            sb.AppendLine();
        }

        var keyword = model.IsStruct ? "partial struct" : "partial class";
        sb.AppendLine($"{keyword} {model.ClassName}");
        sb.AppendLine("{");

        if (model.Concurrent)
            WriteConcurrentBody(sb, model);
        else
            WriteNonConcurrentBody(sb, model);

        sb.AppendLine("}");
        return sb.ToString();
    }

    // ── Non-concurrent ────────────────────────────────────────────────────────

    private static void WriteNonConcurrentBody(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeShort;
        var tr = m.TriggerTypeShort;

        // State field + Current property
        sb.AppendLine($"    private {st} _state = {st}.{m.InitialState};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>Current state of the machine.</summary>");
        sb.AppendLine($"    public {st} Current => _state;");
        sb.AppendLine();

        // TryFire
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine($"    /// Attempt to fire <paramref name=\"trigger\"/> from the current state.");
        sb.AppendLine($"    /// Returns <c>true</c> if the transition occurred; <c>false</c> if no matching transition or a guard rejected it.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    public bool TryFire({tr} trigger)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        return (Current, trigger) switch");
        sb.AppendLine($"        {{");

        foreach (var t in m.Transitions)
        {
            if (t.HasGuard)
            {
                sb.AppendLine($"            ({st}.{t.From}, {tr}.{t.On})");
                sb.AppendLine($"                when Guard{t.On}({st}.{t.From}, {tr}.{t.On})");
                sb.AppendLine($"                => Fire({st}.{t.From}, {st}.{t.To}, trigger),");
            }
            else
            {
                sb.AppendLine($"            ({st}.{t.From}, {tr}.{t.On}) => Fire({st}.{t.From}, {st}.{t.To}, trigger),");
            }
        }

        sb.AppendLine($"            _ => false");
        sb.AppendLine($"        }};");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // Fire helper
        sb.AppendLine($"    private bool Fire({st} from, {st} to, {tr} trigger)");
        sb.AppendLine($"    {{");
        sb.AppendLine($"        OnExit(from, trigger);");
        sb.AppendLine($"        _state = to;");
        sb.AppendLine($"        OnEnter(to, from);");
        sb.AppendLine($"        return true;");
        sb.AppendLine($"    }}");
        sb.AppendLine();

        // OnExit dispatcher
        WriteOnExitDispatcher(sb, m);
        sb.AppendLine();

        // OnEnter dispatcher
        WriteOnEnterDispatcher(sb, m);
        sb.AppendLine();

        // Partial stubs (guards + hooks) — detailed stubs in Task 7; emit minimal stubs now
        WritePartialStubs(sb, m);
    }

    private static void WriteOnExitDispatcher(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeShort;
        var tr = m.TriggerTypeShort;
        var exitStates = m.Transitions.Select(static t => t.From).Distinct(StringComparer.Ordinal).ToArray();

        sb.AppendLine($"    private void OnExit({st} state, {tr} trigger)");
        sb.AppendLine($"    {{");
        if (exitStates.Length > 0)
        {
            sb.AppendLine($"        switch (state)");
            sb.AppendLine($"        {{");
            foreach (var s in exitStates)
                sb.AppendLine($"            case {st}.{s}: OnExit{s}(trigger); break;");
            sb.AppendLine($"        }}");
        }
        sb.AppendLine($"    }}");
    }

    private static void WriteOnEnterDispatcher(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeShort;
        var enterStates = m.Transitions.Select(static t => t.To).Distinct(StringComparer.Ordinal).ToArray();

        sb.AppendLine($"    private void OnEnter({st} state, {st} from)");
        sb.AppendLine($"    {{");
        if (enterStates.Length > 0)
        {
            sb.AppendLine($"        switch (state)");
            sb.AppendLine($"        {{");
            foreach (var s in enterStates)
                sb.AppendLine($"            case {st}.{s}: OnEnter{s}(from); break;");
            sb.AppendLine($"        }}");
        }
        sb.AppendLine($"    }}");
    }

    private static void WritePartialStubs(StringBuilder sb, StateMachineModel m)
    {
        var st = m.StateTypeShort;
        var tr = m.TriggerTypeShort;

        sb.AppendLine();
        sb.AppendLine($"    // ── Partial hooks — implement what you need, leave the rest ─────────────");

        // Guard stubs — one per guarded transition (only emitted when When = true)
        var guardedTransitions = m.Transitions.Where(static t => t.HasGuard).ToArray();
        foreach (var t in guardedTransitions)
        {
            sb.AppendLine($"    /// <summary>Guard for the {t.From} → {t.To} transition. Return <c>false</c> to block it.</summary>");
            sb.AppendLine($"    partial bool Guard{t.On}({st} from, {tr} on);");
        }

        // OnExit stubs — one per unique From state
        var exitStates = m.Transitions.Select(static t => t.From).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in exitStates)
        {
            sb.AppendLine($"    /// <summary>Called before leaving <c>{s}</c>.</summary>");
            sb.AppendLine($"    partial void OnExit{s}({tr} on);");
        }

        // OnEnter stubs — one per unique To state
        var enterStates = m.Transitions.Select(static t => t.To).Distinct(StringComparer.Ordinal).ToArray();
        foreach (var s in enterStates)
        {
            sb.AppendLine($"    /// <summary>Called after entering <c>{s}</c>.</summary>");
            sb.AppendLine($"    partial void OnEnter{s}({st} from);");
        }
    }

    // ── Concurrent (Task 8) ───────────────────────────────────────────────────

    private static void WriteConcurrentBody(StringBuilder sb, StateMachineModel m)
    {
        // Implemented in Task 8
        sb.AppendLine($"    // Concurrent mode — implemented in Task 8");
    }
}
