namespace ZeroAlloc.StateMachine.Generator;

internal static class StateMachineWriter
{
    public static string Write(StateMachineModel model)
    {
        // Implemented in Tasks 6, 7, 8
        return $"// <auto-generated />\n// StateMachine: {model.ClassName}";
    }
}
